apiVersion: v1
kind: Service
metadata:
  name: dynamic-tps-app-service
spec:
  selector:
    app: dynamic-tps-app
  ports:
    - port: 8095
      targetPort: 8095
      nodePort: 30004
  type: NodePort
  