apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: dynamic-tps-app
spec:
  selector:
    name: redis-pod
    app: redis-app
  ports:
    - port: 6379
      targetPort: 6379
  