apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-tps-redis-deploy
  labels:
    name: dynamic-tps-redis-deploy
    app: redis-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: redis-app
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: redis-app
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
      