server:
  port: 8095
spring:
  application:
    name: @project.artifactId@
  data:
    redis:
      host: localhost
      port: 6379

test-service:
  uri: http://localhost:8095

processor:
  target-tps: 100